### ISSUE TITLE
Add Elliot's photo and bio

### ISSUE THREAD

**Issue by amshin98** [cal-poly-slo-cs-tutoring/Website#16]
Elliot Brainerd

- [x] Get Elliot 's bio
- [x] Get Elliot 's picture
- [x] Add both to the website

**Comment by nvaa36** [comment]
Bio:
Hello! I am a fourth year Computer Science major and have been programming since I was about 16. I joined the tutoring program in the Spring of 2020 and am so excited to help students get through the same problems I faced as a beginning programmer. Outside of that, I am an avid reader, guitar player, and volleyball player.

**Comment by nvaa36** [comment]
The photo is in the slack.
